--- 
- name: "Jolokia plugin"
  template: 
    dest: /home/temp.conf
    src: telegraf.conf_jolokia.jk2
  when: "JolokiaServerIP is defined"
- name: "add Jolokia plugin to telegraf.conf"
  shell: "cat temp.conf >> /etc/telegraf/telegraf.conf"
  args: 
    chdir: /home/
  when: "JolokiaServerIP is defined"

