---

- name: "replace packetbeat.yml"
  template: 
    src: packetbeat/packetbeat.yml.jk2
    dest: /etc/packetbeat/packetbeat.yml
  when: packetbeat

- name: "setup default packetbeat dashboards"
  command: packetbeat setup --dashboards
  when: (filebeat_dashboard_import=="true") and (hostvars.localhost.elasticsearch.status==200) and (hostvars.localhost.kibana.status==200) 

- name: "restart packetbeat"
  service:
    name: packetbeat
    state: restarted
  when: packetbeat
