{
 "title": "ApplicationMonitoring",
 "description": "This dashboard provides key metrics for monitoring Java Stack - Jolokia JVM, Redis, Mongodb, Tomcat,Apache Httpd, using InfluxDB and Telegraf.",
 "time": { "from": "now/w", "to": "now/w" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "show tag values from system with key = \"host\""
   },
   {
    "name": "Jolokia",
    "label": "JolokiaAgentHost",
    "query": "SHOW TAG VALUES FROM \"jvm_runtime\" WITH KEY = \"host\""
   },
   {
    "name": "tomcatHost",
    "label": "TomcatHost",
    "query": "SHOW TAG VALUES FROM \"tomcat_connector\" WITH KEY = \"host\""
   },
   {
    "name": "MongoDBHost",
    "label": "MongoDB Host",
    "query": "SHOW TAG VALUES FROM \"mongodb\" WITH KEY = \"host\""
   },
   {
    "name": "RedisHost",
    "label": "RedisHost",
    "query": "SHOW TAG VALUES FROM \"redis\" WITH KEY = \"host\""
   },
   {
    "name": "HttpServer",
    "label": "Apache Httpd",
    "query": "SHOW TAG VALUES FROM \"apache\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "JVMJolokia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Heap Memory Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory",
       "query": "SELECT mean(\"heap_memory_usage_used\") FROM \"jolokia\" WHERE (\"host\" =~ /^$Jolokia$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Heap Memory Init",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.init" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Heap Memory Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Garbage Collection Count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_garbage_collector",
       "select": [
        [
         { "params": [ "CollectionCount" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Collection Usage Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Collection Usage Memory used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_pool",
       "select": [
        [
         { "params": [ "CollectionUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Peak Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "PeakUsage Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "PeakUsage Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jvm_memory_pool",
       "select": [
        [
         { "params": [ "PeakUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Free RAM Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    },
    {
     "title": "Jolokia Host Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Jolokia$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Memory Peak",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "alias": "Used Memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "used_memory_peak" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connected Slaves",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Connected Slaves",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "connected_slaves" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Total net output bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "total_net_output_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Evicted/Expired Keys",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Expired keys",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "expired_keys" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "Evicted Keys",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "evicted_keys" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "keys hits",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "keyspace_hits" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "Keys misses",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "keyspace_misses" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "alias": "command processed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "total_commands_processed" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Persistence Metrics",
     "type": "graph",
     "description": "Unix timestamp of last save to disk\nNumber of changes to the database since last dump",
     "gridPos": { "h": 6, "w": 14, "x": 4, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "rdb_last_save_time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "rdb_last_save_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "rdb_changes_since_last_save",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "rdb_changes_since_last_save" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Error Metrics",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "rejected connections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "rejected_connections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "blocked clients",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "redis",
       "select": [
        [
         { "params": [ "blocked_clients" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "singlestat",
     "description": "cpus for Redis machine.",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Memory Free",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 14 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Redis Host Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$RedisHost$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Current Threads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_connector",
       "select": [
        [
         { "params": [ "current_thread_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Current Threads Busy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_connector",
       "select": [
        [
         { "params": [ "current_threads_busy" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg Processing Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "alias": "Avg. Processing Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_connector",
       "select": [
        [
         { "params": [ "processing_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes Sent & Received(per sec)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Bytes Sent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_connector",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Bytes Received",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_connector",
       "select": [
        [
         { "params": [ "bytes_received" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Memory Free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Memory Max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory",
       "select": [
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Memory Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tomcat_jvm_memory",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Tomcat Host Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 10, "y": 15 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 14, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 18, "y": 15 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "available_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput-Requests per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Commands per sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "commands_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Queries per sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queries_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "inserts_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "inserts_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "updates_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "updates_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "deletes_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "deletes_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput-Read/Writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active Reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "active_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Active Writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "active_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Queued Reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queued_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Queued Writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "queued_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Open Connections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "open_connections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Net-in-Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "net_in_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Net-Out-Bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "net_out_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Throughput- Flushes , TTL per sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "flushes_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "flushes_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "ttl_deletes_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "ttl_deletes_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "ttl_passes_per_sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "ttl_passes_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
     "format": "decmbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mongodb",
       "select": [
        [
         { "params": [ "vsize_megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "MongoDB Host Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 20 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "Total RAM Memory",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 20 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$MongoDBHost$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Apache HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ConnsAsyncClosing",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ConnsAsyncClosing " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "ConnsAsyncKeepAlive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ConnsAsyncKeepAlive " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "ConnsAsyncWriting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ConnsAsyncWriting " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "ConnsTotal",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ConnsTotal " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Busy vs Idle Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 10, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "BusyWorkers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "BusyWorkers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "IdleWorkers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "IdleWorkers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "BytesPerSec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "BytesPerSec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "BytesPerReq",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "BytesPerReq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "CPULoad",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "CPULoad" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "CPUSystem",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "CPUSystem " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "CPUUser",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "CPUUser " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$Host$/" }
       ]
      }
     ]
    },
    {
     "title": "Requests per sec",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Requests per sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "ReqPerSec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Load Metrics",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "Load1 " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "Load5 " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "Load15 " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Scoreboard",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "scboard_open",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_open" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_starting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_starting" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_closing",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_closing" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_reading",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_reading" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_waiting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_waiting " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_finishing",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_finishing" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_idle_cleanup",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_idle_cleanup" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_keepalive",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_keepalive " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "scboard_logging",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "scboard_logging " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Requests per sec",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "CPULoad" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "apache",
       "select": [
        [
         { "params": [ "Uptime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    },
    {
     "title": "Host Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Load1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "Load5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "Load5 " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      },
      {
       "alias": "Load15",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "Load15 " ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$HttpServer$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}