{
 "title": "Containers Overview  Monitoring",
 "tags": [
  "docker",
  "telegraf"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values with key = \"engine_host\"\t"
   },
   {
    "name": "container",
    "label": "Service",
    "query": "show tag values with key = \"container_name\" WHERE engine_host =~ /^$host$/ "
   }
  ]
 },
 "panels": [
  {
   "title": "CPU $container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_engine_host]] $container ([[tag_com.docker.swarm.task.id]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of running containers on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of images on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "SELECT mean(\"n_images\") FROM \"docker\" WHERE \"engine_host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage % for $container",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage % for $container",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
      { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU global usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]] [[tag_com.viavi.bamboo-build-version]] ([[tag_com.docker.swarm.task.id]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
      { "params": [ "com.viavi.bamboo-build-version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Container status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running containers",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "SELECT mean(\"n_containers_running\") FROM \"docker\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Paused containers",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "SELECT mean(\"n_containers_running\") FROM \"docker\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Stopped containers",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "query": "SELECT mean(\"n_containers_running\") FROM \"docker\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]] [[tag_com.viavi.bamboo-build-version]] ([[tag_com.docker.swarm.task.id]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
      { "params": [ "com.viavi.bamboo-build-version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network overview for $host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_com.docker.swarm.service.name]] ([[tag_com.docker.swarm.task.id]]) OUT",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT derivative(mean(\"tx_bytes\"), 10s) FROM \"docker_container_net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"com.docker.swarm.service.name\" fill(null)",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "[[tag_com.docker.swarm.service.name]] ([[tag_com.docker.swarm.task.id]]) IN",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
      { "params": [ "engine_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}