{
 "title": "Custom Metrics",
 "tags": [ "stagemonitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "{\"find\": \"terms\", \"field\": \"application\"}"
   },
   {
    "name": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host\"}"
   },
   {
    "name": "Instance",
    "query": "{\"find\": \"terms\", \"field\": \"instance\"}"
   },
   {
    "name": "Signature",
    "query": "{\"find\": \"terms\", \"field\": \"signature\", \"query\": \"name: timer\"}"
   },
   { "name": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "Documentation (click me to expand)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "# Custom Metrics\n\nThis dashboard includes all metrics generated by the annotations `@Timed`, `@Metered`, `@ExceptionMetered` and `@Gauge`.\n\nSee also [Track your own metrics](https://github.com/stagemonitor/stagemonitor/wiki/Track-your-own-metrics)\n\n\n---\n\n[Edit this page](https://github.com/stagemonitor/stagemonitor/edit/master/stagemonitor-core/src/main/resources/grafana/ElasticsearchCustomMetricsDashboardDocumentation.md)\n"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Timer",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{term signature}} ({{field}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "signature",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "p75",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      }
     ],
     "query": "name: timer AND application: $Application AND host: $Host AND instance: $Instance AND signature: $Signature",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{term name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "name",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: gauge_*  AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Method invocation rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Invocations/s" }
   ],
   "targets": [
    {
     "alias": "{{term signature}} ({{field}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "signature",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: rate AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Exception rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Exceptions/s" }
   ],
   "targets": [
    {
     "alias": "{{term signature}} ({{field}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "signature",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: exception_rate AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}