{
 "title": "Devops Toolchain Monitoring",
 "tags": [
  "docker",
  "telegraf"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "engine_host",
    "label": "engine_host",
    "query": "show tag values with key = \"engine_host\"\t"
   },
   {
    "name": "container",
    "label": "Service",
    "query": "show tag values with key = \"container_name\" WHERE engine_host =~ /^$engine_host$/ "
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\""
   },
   {
    "name": "tomcatHost",
    "label": "tomcatHost",
    "query": "SHOW TAG VALUES FROM \"tomcat_connector\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Tools Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU  Usage of $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_engine_host]] $container",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "engine_host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage of $container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "[[tag_com.docker.swarm.service.name]] [[tag_com.viavi.bamboo-build-version]] ([[tag_com.docker.swarm.task.id]])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
        { "params": [ "engine_host" ], "type": "tag" },
        { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
        { "params": [ "com.viavi.bamboo-build-version" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network overview for $container",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "[[tag_com.docker.swarm.service.name]] ([[tag_com.docker.swarm.task.id]]) OUT",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
        { "params": [ "engine_host" ], "type": "tag" },
        { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "query": "SELECT derivative(mean(\"tx_bytes\"), 10s) FROM \"docker_container_net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"com.docker.swarm.service.name\" fill(null)",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      },
      {
       "alias": "[[tag_com.docker.swarm.service.name]] ([[tag_com.docker.swarm.task.id]]) IN",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
        { "params": [ "com.docker.swarm.task.id" ], "type": "tag" },
        { "params": [ "engine_host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory usage % for $container",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU usage % for $container",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "container_name", "operator": "=~", "value": "/^$container$/" },
        { "condition": "AND", "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tools_Host_Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime_format" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "mem",
       "query": "SELECT last(\"total\") FROM \"mem\" WHERE \"host\" =~ /^$host$/",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "cpus",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "load1",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "load5",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "load15",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "users",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "n_users" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk used_percent",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "SELECT max(used_percent) FROM \"disk\" WHERE \"host\" =~ /^$host$/ and \"device\" != 'rootfs'  and $timeFilter",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory used_percent",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT last(used_percent) FROM \"mem\" WHERE \"host\" =~ /^$host$/",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total threads",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "select last(uptime_format) from system where  host =~ /^$host$/",
       "select": [
        [
         { "params": [ "total_threads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of images on $engine_host",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "query": "SELECT mean(\"n_images\") FROM \"docker\" WHERE \"engine_host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "n_images" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of running containers on $engine_host",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "Container status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Running containers",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "query": "SELECT mean(\"n_containers_running\") FROM \"docker\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "n_containers_running" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      },
      {
       "alias": "Stoped containers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_stopped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      },
      {
       "alias": "Paused containers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_paused" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "engine_host", "operator": "=~", "value": "/^$engine_host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU  Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPU Usage",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "engine_host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Stats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes_Recv",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Bytes_sent",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Packets_recv",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Packets_sent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tools Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jenkins Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://jenkins:8080" }
       ]
      }
     ]
    },
    {
     "title": "Jira Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Jira Status",
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://jira:8080" }
       ]
      }
     ]
    },
    {
     "title": "GitLab Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "gitlab Status",
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://10.106.131.14:30080" }
       ]
      }
     ]
    },
    {
     "title": "Tomcat Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://tomcat:8080" }
       ]
      }
     ]
    },
    {
     "title": "Nexus Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://nexus:8081" }
       ]
      }
     ]
    },
    {
     "title": "SonarQube Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://sonarqube:9000" }
       ]
      }
     ]
    },
    {
     "title": "Gerrit Status",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "http://10.106.131.14:5085" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Application Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Tomcat Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Current Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "query": "SELECT max(\"current_thread_count\") FROM \"tomcat_connector\" WHERE (\"host\" =~ /^$tomcatHost$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "current_thread_count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    },
    {
     "alias": "Current Threads Busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "query": "SELECT mean(\"current_threads_busy\") FROM \"tomcat_connector\" WHERE (\"host\" =~ /^$tomcatHost$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "current_threads_busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Processing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Avg. Processing Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "processing_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Sent & Received(per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Bytes Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    },
    {
     "alias": "Bytes Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_connector",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Memory Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    },
    {
     "alias": "Memory Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    },
    {
     "alias": "Memory Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tomcat_jvm_memory",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$tomcatHost$/" }
     ]
    }
   ]
  }
 ]
}