{
 "title": "EhCache",
 "tags": [ "stagemonitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "{\"find\": \"terms\", \"field\": \"application\"}"
   },
   {
    "name": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host\"}"
   },
   {
    "name": "Instance",
    "query": "{\"find\": \"terms\", \"field\": \"instance\"}"
   },
   { "name": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "Documentation (click me to expand)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "# EhCache Performance Dashboard\n\nThis dashboard contains metrics about [EhCache](http://www.ehcache.org/).\n\n## Cache Hit Rate (worst 10)\nThis panel contains cache names and their hit rate.\nIt is important to let the application and caches \"warm up\" before deciding if caching improves the response time of the application.\nA low hit rate is a possible indicator for:\n* too early evaluation of cache usefulness (use warm caches!)\n* too frequent invalidation of cache entries\n* too many cache entries\n* too small caches\n* too short cache entry lifetime\n* too infrequent access of cache entries\n\n## Cache Size\nThis panel contains the 10 biggest caches by heap size.\n\n## Gets per second (highest 10)\nThis panel contains the 10 most frequent accessed caches.\n\n## Expires per second (highest 10)\nThis panel contains the 10 caches with the highest expiration rate.\n\n\n\n---\n\n[Edit this page](https://github.com/stagemonitor/stagemonitor/edit/master/stagemonitor-ehcache/src/main/resources/grafana/ElasticsearchEhCacheDocumentation.md)\n"
    }
   ]
  },
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cache Hit Rate (worst 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cache_name",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: cache_hit_ratio AND tier: All AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cache Size (highest 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cache_name",
       "id": "3",
       "settings": { "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: cache_size_bytes AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Gets per Second (highest 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cache_name",
       "id": "3",
       "settings": { "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m5_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: cache_get tier: All AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Expires per Second (highest 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cache_name",
       "id": "3",
       "settings": { "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m5_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: cache_delete AND reason: expire AND tier: All AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}