{
 "title": "Host Influx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem_usage_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "ers-devops-coe-machine2" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Swap Pages per second (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap_pages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_io",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_usage_percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Disk Queue (max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_io",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  },
  {
   "title": "Network Packet Dropped per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_io",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "dropped" },
      { "condition": "AND", "key": "application", "operator": "=", "value": "GameOfLife" }
     ]
    }
   ]
  },
  {
   "title": "Network Packet Errors per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_io",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "errors" },
      { "condition": "AND", "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "ifname", "operator": "=", "value": "br-11ad8dae49b1" },
      { "condition": "AND", "key": "application", "operator": "=", "value": "GameOfLife" }
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_info_cores",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "GameOfLife" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "dev" }
     ]
    }
   ]
  }
 ]
}