{
 "title": "JVM",
 "tags": [ "stagemonitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "{\"find\": \"terms\", \"field\": \"application\"}"
   },
   {
    "name": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host\"}"
   },
   {
    "name": "Instance",
    "query": "{\"find\": \"terms\", \"field\": \"instance\"}"
   },
   { "name": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "Documentation (click me to expand)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "# JVM dashboard\nThis dashboard contains information about memory usage and garbage collection metrics of the JVM.\n\n## Heap Usage and Non-Heap Usage\nBoth heap and non heap usage have three metrics with the same meaning. The following documentation is taken from <https://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryUsage.html>\n\n* *committed*:\nrepresents the amount of memory (in bytes) that is guaranteed to be available for use by the Java virtual machine. The amount of committed memory may change over time (increase or decrease). The Java virtual machine may release memory to the system and committed could be less than init. committed will always be greater than or equal to used.\n\n* *used*:\nrepresents the amount of memory currently used (in bytes).\n\n* *max*:\nrepresents the maximum amount of memory (in bytes) that can be used for memory management. Its value may be undefined. The maximum amount of memory may change over time if defined. The amount of used and committed memory will always be less than or equal to max if max is defined. A memory allocation may fail if it attempts to increase the used memory such that used > committed even if used <= max would still be true (for example, when the system is low on virtual memory).\n\n## Heap Usage\nMemory used by the JVM to store runtime data (objects).\n\n## Non-Heap Usage\nMemory used by the JVM to store loaded classes and other meta-data.\n\n## GC (Garbage Collector)\nThe garbage collector reclaims memory occupied by objects that are no longer referenced.\nCollector types are explained here:\n<http://jvmmemory.com/>\n\nFor more in depth information consult the official documentation:\n<https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/toc.html>\n\n## Memory pools\n\nHeap:\n* *Eden Space*: The pool from which memory is initially allocated for most objects.\n* *Survivor Space*: The pool containing objects that have survived the garbage collection of the Eden space.\n* *Old Generation*: The pool containing objects that have existed for some time in the survivor space.\n\nNon Heap:\n* *Code Cache*: The HotSpot Java VM also includes a code cache, containing memory that is used for compilation and storage of native code.\n* *Compressed class space*: Class information referred to by the objects in the JavaHeap\n* *Metaspace*: Method and other information excluding the above information\n\n\n\n---\n\n[Edit this page](https://github.com/stagemonitor/stagemonitor/edit/master/stagemonitor-jvm/src/main/resources/grafana/ElasticsearchJvmDocumentation.md)\n"
    }
   ]
  },
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "type",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: jvm_memory_heap AND !type: usage AND !type: init AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Non-Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "type",
       "id": "3",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: jvm_memory_non_heap AND !type: usage AND !type: init AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "collector",
       "id": "3",
       "order": "asc",
       "orderBy": "_term",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "size": "0",
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "order": "asc",
       "orderBy": "_term",
       "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 },
       "size": "0",
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name: jvm_gc_time AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "memory_pool",
       "id": "3",
       "order": "asc",
       "orderBy": "_term",
       "settings": { "order": "asc", "orderBy": "_term", "size": "0" },
       "size": "0",
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name: jvm_memory_pools  AND type: usage AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}