{
 "title": "JVM_Influx",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "SHOW TAG VALUES FROM \"jvm_gc_time\" WITH KEY = \"application\""
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": "SHOW TAG VALUES FROM \"jvm_gc_time\" WITH KEY = \"instance\""
   },
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"jvm_gc_time\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Non Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_non_heap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "memory_pool" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_pools",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "max" }
     ]
    }
   ]
  }
 ]
}