{
 "title": "Request Metrics",
 "tags": [ "stagemonitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": "{\"find\": \"terms\", \"field\": \"application\"}"
   },
   {
    "name": "Host",
    "query": "{\"find\": \"terms\", \"field\": \"host\"}"
   },
   {
    "name": "Instance",
    "query": "{\"find\": \"terms\", \"field\": \"instance\"}"
   },
   {
    "name": "operation_type",
    "label": "Operation Type",
    "query": "{\"find\": \"terms\", \"field\": \"operation_type\"}"
   },
   {
    "name": "operation_name",
    "label": "Operation Name",
    "query": "{\"find\": \"terms\", \"field\": \"operation_name\", \"query\": \"operation_type: $operation_type\"}"
   },
   { "name": "Interval" }
  ]
 },
 "panels": [
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "This panel contains the percentiles of all response timings.\nThe p99 percentile is the time, below which 99% of the request times will be.\nTherefore can a strong increase from p95 to p99 indicate that most of the application performs good with the exception of a few slow endpoints.\nA lower response time is generally desired.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{field}}",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "max",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "p999",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "99.9" ] },
       "type": "percentiles"
      },
      {
       "field": "p99",
       "id": "3",
       "meta": {},
       "settings": { "percents": [ "99" ] },
       "type": "percentiles"
      },
      {
       "field": "p95",
       "id": "4",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      },
      {
       "field": "p75",
       "id": "5",
       "meta": {},
       "settings": { "percents": [ "75" ] },
       "type": "percentiles"
      },
      {
       "field": "p50",
       "id": "6",
       "meta": {},
       "settings": { "percents": [ "50" ] },
       "type": "percentiles"
      }
     ],
     "query": "name: response_time AND operation_type: $operation_type AND operation_name: \"$operation_name\" AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Throughput (requests per second)",
   "type": "graph",
   "description": "Shows the total and the faulty requests per second.\n\nNote that this is the average and not the sum across the selected application host and instance.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "throughput",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: response_time AND operation_name: \"$operation_name\" AND operation_type: \"$operation_type\" AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "error rate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: error_rate AND operation_name: \"$operation_name\" AND operation_type: \"$operation_type\" AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Slowest Requests (Median)",
   "type": "graph",
   "description": "This panel groups the slowest requests for the median of all requests.\nFrequently accessed slow endpoints may provide potential for optimization.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "p50",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: response_time AND !operation_name: All AND operation_type: $operation_type AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Highest Throughput",
   "type": "graph",
   "description": "This panel shows the most frequently executed operations",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: response_time AND !operation_name: All AND operation_type: $operation_type AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Slowest Requests (p95)",
   "type": "graph",
   "description": "This panel groups the slowest requests for the 95th percentile of all requests.\nFrequently accessed slow endpoints may provide potential for optimization.\nYou can use the stagemonitor Kibana Request Analysis Dashboard for a more in-depth analysis of the slow response time cause.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "p95",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: response_time AND !request_name: All AND operation_type: $operation_type AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most Errors",
   "type": "graph",
   "description": "This panel contains the endpoints with the highest error count.\nA high error count is an indicator for application logic errors.\nYou can use the stagemonitor Kibana Request Analysis Dashboard for a more in-depth analysis of the error cause.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: error_rate AND !operation_name: All AND operation_type: $operation_type AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Most external requests",
   "type": "graph",
   "description": "This panel shows the operations which issue the most requests to external services\nTry to minimize the number of external requests to save network roundtrip times.\nYou can do so by trying to batch loading resources.\nA high count of jdbc requests could for example indicate a classical n+1 problem.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "operation_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "m1_rate",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name: external_requests_rate AND !operation_name: All AND application: $Application AND host: $Host AND instance: $Instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Documentation (click me to expand)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documentation",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "content": "# Request Metrics dashboard\n\nThis dashboards allows the observation of the response time and throughput of your services.\n\nTo analyze the individual requests go to the corresponding Kibana dashboard: <http://your-kibana-host:5601/app/kibana#/dashboard/Request-Analysis>.\n\n\n---\n\n[Edit this page](https://github.com/stagemonitor/stagemonitor/edit/master/stagemonitor-tracing/src/main/resources/grafana/ElasticsearchRequestDashboardDocumentation.md)\n"
    }
   ]
  }
 ]
}