--- 
- name: "Redis plugin"
  template: 
    dest: /home/temp.conf
    src: telegraf.conf_redisconfig.jk2
  when: "RedisIP is defined"
- name: "add Redisplugin to telegraf.conf"
  shell: "cat temp.conf >> /etc/telegraf/telegraf.conf"
  args: 
    chdir: /home/
  when: "RedisIP is defined"

